/**
 * @description       : 
 * @author            :
**/

@isTest(seeAllData=true)
private class AAATest {

	private static String RECORD_TYPE_TITULACION_IDIOMA   = Constantes.RECORD_TYPE_TITULACION_IDIOMA; // DeveloperName del tipo de registro idiomas para la titulación
	private static String RECORD_TYPE_SOLICITUD_IDIOMA    = Constantes.RECORD_TYPE_SOLICITUD_IDIOMA;  // DeveloperName del tipo de registro idiomas para la solicutud
	private static String RECORD_TYPE_LEAD_IDIOMA         = Constantes.RECORD_TYPE_LEAD_IDIOMA;       // DeveloperName del tipo de registro idiomas para la titulación

    @isTest static void test_comprobarSolicitaInformacion()
    {
    }

}
